name: Build and Deploy 🚀

on:
    schedule:
        - cron: '0 15 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
                  envkey_TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
                  envkey_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                  envkey_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
                  file_name: .env

            - name: Build the docker container
              run: docker build .

            - name: Run the script 🚀
              run: docker-compose up
